name: Aula de GCS
on: push

defaults: 
  run:
    shell: bash
    #working-directory: 

jobs:
  primeiro:
    runs-on: ubuntu-latest
    name: Primeiro Job Escrito
    steps:
      - name: Mostrar Rodando
        run: echo teste
      - name: Mostrar Rodando
        run: echo "${{ github.event_name}} foi disparado"
      - name: Listar Conteúdo
        run: ls -la ${{ github.workspace }}
      - name: Listar Rede
        run: ipconfig
    
  segundo:
    runs-on: windows-latest
    name: Segund Job
    steps: 
      - name: Cirando Vairiaveis Ambiente
        env:
          VAR1: Isso é
          VAR2: Github Actions
        run:  echo $VAR1 $VAR2 
      - name: View IP
        run: ipconfig
        
  terceiro:
    runs-on: ubuntu-latest
    name: Terceiro
    steps:
      - run: echo "${{ github.event_name }} foi disparado"
      - run: echo " No ${{ runner.os }} server hosted by Github has this job"
      - run: echo "Details of your Repo -  repo-name - ${{ github.repository }} and branch name is ${{ github.ref }} and your repository is ${{ github.repository }}"
      - name: Check out Repo
        uses: actions/checkout@v3
      - run: echo "The runner has cloned your ${{ github.repository }} repo"
      - run: echo "The workflow can now test your code with the runner."
      - name: List files in the repo
        run: |
          ls ${{ github.workspace }}
      - run: echo "This job has a ${{ job.status }} status"
  
  quarto:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 15.x, 18.x, 20.x]
        #Versions 10, 12, not suported anymore

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      
